name: Configure Default Branch Protection

on:
  schedule:
    # Run the workflow every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  configure_ruleset:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Set up GitHub CLI
      run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

    - name: Configure repository settings
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh api "repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/rulesets" \
          --method POST \
          --silent \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          --input ./branch-rulesets/default-branch.json
