name: Configure Branch Protection Rulesets

on:
  schedule:
    # Run the workflow every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  configure_ruleset:
    runs-on: ubuntu-latest

    steps:
    - name: Convert App token
      id: create_token 
      uses: getsentry/action-github-app-token@v3.0.0
      with:
        app_id: ${{ vars.FSDH_REPO_ADMIN_APP_ID }}
        private_key: ${{ secrets.FSDH_REPO_ADMIN_APP_KEY }}

    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Set up GitHub CLI
      run: gh auth login --with-token <<< "${{ steps.create_token.outputs.token }}"

    - name: Delete all existing rulesets
      env:
        GH_TOKEN: ${{ steps.create_token.outputs.token }}
      run: |
        # Get the list of existing rulesets
        existing_rulesets=$(gh api "repos/${{ github.repository }}/rulesets" --jq '.[].id')
        
        # Loop through and delete each ruleset
        for ruleset_id in $existing_rulesets; do
          echo "Deleting ruleset ID $ruleset_id"
          gh api "repos/${{ github.repository }}/rulesets/$ruleset_id" \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" || exit 1
        done

    - name: Loop through and configure repository settings
      env:
        GH_TOKEN: ${{ steps.create_token.outputs.token }}
      run: |
        for file in .github/workflows/branch-rulesets/*.json; do
          echo "Applying ruleset from $file"
          gh api "repos/${{ github.repository }}/rulesets" \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            --input "$file" || exit 1
        done