name: Configure Branch Protection

on:
  schedule:
    # Run the workflow every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  configure_ruleset:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Authenticate GitHub CLI
      run: echo "${{ secrets.REPO_ADMIN_ACCESS_TOKEN }}" | gh auth login --with-token

    - name: Configure repository settings
      run: |
        gh api "repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/rulesets" \
          --method POST \
          --silent \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -f "name=super cool ruleset" \
          -f "target=branch" \
          -f "enforcement=active" 