name: Configure Default Branch Protection

on:
  schedule:
    # Run the workflow every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  configure_ruleset:
    runs-on: ubuntu-latest
    
    steps:

    - name: Convert App token
      id: create_token 
      uses: getsentry/action-github-app-token@v3.0.0
      with:
        app_id: ${{ env.FSDH_REPO_ADMIN_APP_ID }}
        private_key: ${{ secrets.FSDH_REPO_ADMIN_APP_KEY }}
    - run: "echo 'The created token is masked: ${{ steps.create_token.outputs.token }}'"

    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Set up GitHub CLI
      run: gh auth login --with-token <<< "${{ steps.create_token.outputs.token }}"

    - name: Configure repository settings
      env:
        GH_TOKEN: ${{ steps.create_token.outputs.token }}
      run: |
        gh api "repos/${{ github.repository }}/rulesets" \
          --method POST \
          --silent \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          --input .github/workflows/branch-rulesets/default-branch.json
